## Binary classifier - Logistic

In [70]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics


df = pd.read_csv('utils/C_npf_train.csv')
Y2 = df['class2']
Y4 = df['class4']
df = df.drop(['class4', 'class2'], axis=1)
x_train, x_test, y_train, y_test = train_test_split(df, Y2, test_size=0.25, random_state=0)
df

CO2168.mean  CO2168.std  CO2336.mean  CO2336.std  CO242.mean  CO242.std  \
0     384.462000    2.284996   384.164462    2.135062  385.274688   2.211695   
1     374.884615    0.415185   374.703333    0.385179  375.621266   0.665720   
2     373.496585    0.189497   373.382593    0.172958  373.961481   0.235107   
3     378.600367    1.934180   378.464862    1.946536  379.785872   2.865022   
4     373.128684    1.096617   372.980000    1.047750  373.701830   1.259198   
..           ...         ...          ...         ...         ...        ...   
453   377.541538    6.391551   377.802756    6.187754  380.131355   8.036365   
454   381.016623    4.411571   381.030844    4.062115  382.901742   5.061991   
455   386.687895   12.065627   386.284079   11.751004  392.981111  14.968791   
456   379.279128   12.045785   379.363087   11.533353  381.268591  14.043508   
457   384.443758    6.413297   384.364392    5.781036  386.384762   7.663215   

     CO2504.mean  CO2504.std   Glob.mean    Glob.std  ...  T672.mean  \
0     383.885077    1.955198   19.245511   11.909549  ... -13.016471   
1     374.674177    0.435480   31.107659   24.624718  ...  -8.997430   
2     373.275062    0.165500   29.800885   22.892316  ... -10.224472   
3     378.316909    1.983430   23.795211   16.178905  ...  -1.535183   
4     372.910000    1.004164  252.480327  138.921953  ...  -2.095641   
..           ...         ...         ...         ...  ...        ...   
453   377.507244    5.398886  270.743458  226.335210  ...  16.470062   
454   381.072078    3.840630  121.227780  131.474300  ...  16.319361   
455   386.336908   11.457833  108.311442   79.331814  ...  13.315270   
456   379.163200   10.932955  114.298822   99.583613  ...  14.421092   
457   384.186892    5.506259  180.454576  181.538036  ...  15.049728   

     T672.std   T84.mean   T84.std  UV_A.mean   UV_A.std  UV_B.mean  UV_B.std  \
0    0.525698 -12.422972  0.376324   1.635563   0.856948   0.026438  0.014617   
1    0.373927  -8.351043  0.575679   1.441109   0.741088   0.022649  0.012479   
2    0.965988  -9.651155  1.238891   2.677545   1.261612   0.044759  0.023748   
3    0.122651  -0.829524  0.134191   2.261805   1.345651   0.030893  0.021903   
4    1.695622  -1.095864  2.090111  12.906779   7.022300   0.333523  0.239981   
..        ...        ...       ...        ...        ...        ...       ...   
453  2.142789  17.077060  2.779125  16.129744  12.203500   0.786032  0.696306   
454  1.089563  17.268471  1.308728   8.688739   8.320799   0.464422  0.496816   
455  0.511146  13.781909  0.838839   7.375727   5.115708   0.366155  0.316015   
456  1.696894  15.094141  1.745526   8.099394   5.851942   0.416961  0.363890   
457  0.969001  16.076217  1.197644  11.665070  10.062797   0.622831  0.595032   

      CS.mean    CS.std  
0    0.003374  0.000733  
1    0.001501  0.000572  
2    0.000764  0.000048  
3    0.002038  0.000751  
4    0.000662  0.000210  
..        ...       ...  
453  0.002360  0.000253  
454  0.002423  0.000425  
455  0.001993  0.000391  
456  0.003484  0.000457  
457  0.004782  0.001082  

[458 rows x 100 columns]

In [71]:

logReg2 = LogisticRegression(max_iter=500)
logReg2.fit(x_train, y_train)

pred2 = logReg2.predict(x_test)

acc2 = logReg2.score(x_test, y_test)
print(acc2)

conf = metrics.confusion_matrix(y_test, pred2)
print(conf)

0.8173913043478261
[[54 12]
 [ 9 40]]


C:\Users\Adiel\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Multi-label classifier - Logistic

In [72]:
x_train4, x_test4, y_train4, y_test4 = train_test_split(df, Y4, test_size=0.25, random_state=0)
logReg4 = LogisticRegression(max_iter=500)
logReg4.fit(x_train4, y_train4)

pred4 = logReg4.predict(x_test4)

acc4 = logReg4.score(x_test4, y_test4)
print(acc4)

conf4 = metrics.confusion_matrix(y_test4, pred4)
print(conf4)

0.6782608695652174
[[21  1  6  7]
 [ 1  2  4  2]
 [ 4  4 12  2]
 [ 4  0  2 43]]


C:\Users\Adiel\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


II: 21 / 35

Ia: 2 / 9

Ib: 12 / 22

Nonevent: 43 / 49